services:
  cv_app_postgres:
    image: postgres:alpine
    container_name: cv_app_postgres
    restart: always
    ports:
      - "5432:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - local-network

  build_cv_app:
    container_name: django_cv_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:${DJANGO_APP_PORT}"
    restart: unless-stopped
    depends_on:
      - db_migration
    volumes:
      - shared-volume:/app
    networks:
      - local-network

  db_migration:
    entrypoint: ./deploy/migrate_db.sh
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - cv_app_postgres
    networks:
      - local-network

  celery-app:
    build: .
    entrypoint: /app/deploy/worker_entry.sh
    depends_on:
      - redis
    volumes:
      - shared-volume:/app
    networks:
      - local-network

  redis:
    image: redis:alpine
    ports:
      - "6379:${REDIS_PORT}"
    networks:
      - local-network

volumes:
  shared-volume:
  pgdata:

networks:
  local-network:
