# Generated by Django 5.1.7 on 2025-04-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('skills', models.CharField(blank=True, max_length=255)),
                ('projects', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('contacts', models.TextField(blank=True)),
            ],
        ),
    ]
