# Generated by Django 5.1.7 on 2025-04-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('http_method', models.CharField(max_length=255)),
                ('path', models.TextField()),
                ('query', models.TextField()),
                ('ip_address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'requests_logs',
            },
        ),
    ]
