# Generated by Django 5.1.7 on 2025-04-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_requestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='status',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
